# fly.toml app configuration file generated for skeet-discord-bot on 2023-11-11T22:07:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skeet-discord-bot"
primary_region = "dfw"

[build]

[[mounts]]
  source = "skeetbot_db"
  destination = "/app/prisma/db"

